/**
 * Arena System Type Definitions
 *
 * Type definitions for the Arena multi-drone trading system
 */

// Type imports

/**
 * Risk parameters for a drone
 */
export interface DroneRiskParams {
  maxRiskPerTrade: number;
  maxTotalRisk: number;
  defaultStopLoss: number;
  maxLeverage: number;
  minLeverage: number;
  maxPositions: number;
}

/**
 * AI configuration for a drone
 */
export interface DroneAIConfig {
  model?: string;
  temperature?: number;
}

/**
 * Configuration for a single drone within an arena
 */
export interface DroneConfig {
  id: string;
  name: string;
  coins: string[];
  promptPack: string; // e.g., 'aggressive', 'conservative', 'default'
  initialBalance: number;
  riskParams: DroneRiskParams;
  aiConfig?: DroneAIConfig;
}

/**
 * Settings for arena execution
 */
export interface ArenaSettings {
  maxConcurrentAICalls?: number; // Default: 2
  cyclePeriod?: number;
  maxDuration?: number; // milliseconds, optional max duration
}

/**
 * Complete configuration for an arena run
 */
export interface ArenaConfig {
  arenaId?: string; // Generated if not provided
  name: string;
  mode: 'paper';
  drones: DroneConfig[];
  settings?: ArenaSettings;
}

/**
 * Metrics for a single drone
 */
export interface DroneMetrics {
  droneId: string;
  name: string;
  cycleCount: number;
  equity: number;
  balance: number;
  pnl: number;
  pnlPercent: number;
  totalSignals: number;
  totalTrades: number;
  winRate: number;
  sharpeRatio: number;
  maxDrawdown: number;
  maxDrawdownValue: number;
  totalReturn: number;
  annualizedReturn: number;
  profitFactor: number;
  aiCost: number;
  aiTokens: number;
  aiCallCount: number;
  lastUpdate: number;
}

/**
 * Historical snapshot of drone state
 */
export interface DroneSnapshot {
  timestamp: number;
  equity: number;
  balance: number;
  pnl: number;
  cycleCount: number;
  openPositions: number;
}

/**
 * Signal generated by a drone
 */
export interface DroneSignal {
  droneId: string;
  timestamp: number;
  cycleCount: number;
  signal: {
    coin: string;
    action: 'LONG' | 'SHORT' | 'CLOSE' | 'HOLD';
    confidence: number;
    reasoning: string;
  };
}

/**
 * Trade executed by a drone
 */
export interface DroneTrade {
  droneId: string;
  timestamp: number;
  trade: {
    id: string;
    symbol: string;
    side: 'long' | 'short';
    size: number;
    entryPrice: number;
    exitPrice?: number;
    pnl?: number;
    pnlPercent?: number;
    reason?: string;
  };
}

/**
 * State of an arena run
 */
export interface ArenaState {
  arenaId: string;
  status: 'running' | 'stopped' | 'completed' | 'failed';
  startTime: number;
  endTime?: number;
  droneCount: number;
  droneMetrics: Map<string, DroneMetrics>;
  error?: string;
}

/**
 * Comparison results between drones
 */
export interface DroneComparison {
  droneId: string;
  name: string;
  ranking: number;
  metrics: DroneMetrics;
  relativePerformance: {
    vsBest: number; // Percentage relative to best performer
    vsMedian: number;
    vsWorst: number;
  };
}

/**
 * Comprehensive analysis results for an arena
 */
export interface ArenaAnalysis {
  arenaId: string;
  startTime: number;
  endTime?: number;
  duration: number; // milliseconds
  winner: {
    droneId: string;
    name: string;
    metrics: DroneMetrics;
  };
  comparison: DroneComparison[];
  correlations: {
    dronePairs: Array<{
      droneA: string;
      droneB: string;
      correlation: number; // -1 to 1
    }>;
  };
  costAnalysis: {
    totalCost: number;
    mostExpensive: {
      droneId: string;
      name: string;
      cost: number;
    };
    costEfficiency: Array<{
      droneId: string;
      name: string;
      costPerPnL: number;
      costPerTrade: number;
    }>;
  };
}

/**
 * Workflow config options for Arena
 */
export interface ArenaWorkflowOptions {
  eventBus?: any; // TypedEventBus instance
  eventPrefix?: string; // Event name prefix for isolation
  loggerContext?: string; // Logger context string
  logger?: any; // UnifiedLogger instance
}
